title: Interactive-visualizations-and-dashboards
description: Plot.ly Homework - Belly Button Biodiversity
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
